language: java

cache:
    directories:
    - $HOME/.m2

jdk:
  - openjdk7
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10
  - oraclejdk11
  - openjdk11
env:
  - MAVEN=3.2.1
  - MAVEN=3.2.2
  - MAVEN=3.2.3
  - MAVEN=3.2.5
  - MAVEN=3.3.1
  - MAVEN=3.3.3
  - MAVEN=3.3.9
  - MAVEN=3.5.0
  - MAVEN=3.5.2
  - MAVEN=3.5.3

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk11
  - jdk: openjdk11

before_install:
  - export M2_HOME=/tmp/maven-${MAVEN}
  - mkdir $M2_HOME
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C $M2_HOME
  - export PATH=$M2_HOME/bin:$PATH

install: true

script: $M2_HOME/bin/mvn -V clean install

notifications:
  email:
    on_success: never
    on_failure: change
    on_start: never
  irc:
    channels:
      - "chat.freenode.net#nicoulaj"
    on_success: always
    on_failure: always
    on_start: never
    use_notice: true
