language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  - MAVEN=3.2.1
  - MAVEN=3.2.2
  - MAVEN=3.2.3
  - MAVEN=3.2.5
  - MAVEN=3.3.1
  - MAVEN=3.3.3
  - MAVEN=3.3.9

matrix:
  exclude:
  - jdk: openjdk6
    env: MAVEN=3.3.1
  - jdk: openjdk6
    env: MAVEN=3.3.3
  - jdk: openjdk6
    env: MAVEN=3.3.9

before_install:
  - export M2_HOME=/tmp/maven-${MAVEN}
  - mkdir $M2_HOME
  - wget -qO- https://archive.apache.org/dist/maven/maven-3/${MAVEN}/binaries/apache-maven-${MAVEN}-bin.tar.gz | tar xz --strip 1 -C $M2_HOME
  - export PATH=$M2_HOME/bin:$PATH

install: true

script: $M2_HOME/bin/mvn -V clean install
