name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        java: [ '8', '9', '10', '11', '12', '13', '14', '15' ]
        maven: [ '3.0.5', '3.1.1', '3.2.5', '3.3.9', '3.5.4', '3.6.3' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - java ${{ matrix.java }} - maven ${{ matrix.maven }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Maven installation cache
      uses: actions/cache@v2
      with:
        path: ~/maven
        key: ${{ runner.os }}-maven-${{ matrix.maven }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Maven repository cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-repo-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-repo-

    - name: Setup JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Setup Maven
      run: |
        [[ ! -f ~/maven/bin/mvn ]] && mkdir ~/maven && wget -qO- https://archive.apache.org/dist/maven/maven-3/${{ matrix.maven }}/binaries/apache-maven-${{ matrix.maven }}-bin.tar.gz | tar xz --strip 1 -C $M2_HOME

    - name: Build
      run: ~/maven/bin/mvn -V --batch-mode clean verify

    - name: Publish snapshot to Github Packages repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.java == '8' && matrix.maven == '3.6.3'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn --batch-mode deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/nicoulaj -DskipTests
