name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        java: [ '8', '11', '17' ]
        maven: [ '3.2.5', '3.3.9', '3.5.4', '3.6.3', '3.8.4' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - java ${{ matrix.java }} - maven ${{ matrix.maven }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Maven installation cache
      uses: actions/cache@v2
      with:
        path: ~/maven
        key: ${{ runner.os }}-maven-installation-${{ matrix.maven }}

    - name: Setup Maven repository cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-repo-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-repo-

    - name: Setup JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Setup Maven
      shell: bash
      run: |
        if [[ ! -f ~/maven/bin/mvn ]]; then mkdir -p ~/maven && curl -s https://archive.apache.org/dist/maven/maven-3/${{ matrix.maven }}/binaries/apache-maven-${{ matrix.maven }}-bin.tar.gz | tar xvz --strip 1 -C ~/maven; fi

    - name: Build
      shell: bash
      run: |
        unset M2_HOME
        ~/maven/bin/mvn -V --batch-mode clean verify
